project:
  type: website
  output-dir: docs
  resources:
  - CNAME

website:
  title: "Nicholas Varabioff"
  favicon: img/favicon.png
  google-analytics:
    tracking-id: "G-B7HHGYRL0C"
    # storage: none
    # anonymize-ip: true
  # cookie-consent: true
  navbar:
    # logo: img/favicon.png
    left:
      - href: index.qmd
        text: Home
      # - href: src/education.qmd
      #   text: Work
    tools:
      - icon: file-earmark-person
        href: https://drive.google.com/file/d/1TguivckW-bYxp2rUKZVGcCc8Z76KA_PW/view?usp=sharing
      - icon: github
        href: https://github.com/nvarabioff/
      - icon: linkedin
        href: https://www.linkedin.com/in/nvarabioff/
      - icon: envelope-at
        href: mailto:nvarabioff@gmail.com
      - icon: strava
        href: https://www.strava.com/athletes/11038877
  page-footer:
    center:
      - text: "This is a Quarto website. To learn more about Quarto websites visit https://quarto.org/docs/websites."

format:
  html:
    page-layout: article
    theme:
      light: flatly
      dark: darkly
    respect-user-color-scheme: true
    css: styles.css
    toc: true
    toc-depth: 2
    toc-location: left
    toc-title: "Contents"
    smooth-scroll: true
