---
title: "Story"
---

# Education

### Candidate for Master of Data Science
**University of British Columbia** [August 2024 - June 2025]

- Key coursework: Machine Learning, Statistics, Databases, Cloud Computing, Data Visualization
- Treasurer, AMS Triathlon Club

### BASc, Systems Design Engineering
**University of Waterloo** [September 2017 - April 2022]

- Graduation with Distinction
- Computing Option
- Management Sciences Option 
- Competitive Chess Team

# Experience

### Data Engineer
**Vivid Seats** [May 2022 - August 2024]

- MySQL relational databases: optimized resource utilization and SQL query performance through indexing and explain plans, performed DDL and DML migrations, monitored database performance with Datadog, AWS Performance Insights, and Cloudwatch.
- AWS infrastructure: orchestrated database version upgrades, used Terraform to manage RDS instance types, replication tasks, autoscaling, custom endpoints, database parameter configurations; optimized performance and minimize costs in stage and production environments.
- Snowflake data warehouse: loaded and backfilled data, maintained and updated table/view hierarchy, resized and provisioned warehouses.
- ETL and data integration: managed Airflow DAG infrastructure for scheduled tasks, integrated with AWS S3 and Snowflake data warehouse, configured Fivetran connectors.
- Techops: configured Jenkins pipelines for automated database migrations, participated in on-call rotation to address critical incidents.

### Software Developer (Co-op)
**HockeyShot** [May 2021 - August 2021]

- Designed database schema and implemented database models on Hive and Firestore databases
- Contributed to embedded code

### Software Developer (Co-op)
**emtelligent** [January 2020 - December 2020]

- Built ETL tools with Python and SQL to automate downloading and cleaning of medical ontology data into MySQL databases
- Integrated databases with Emtelligent’s Natural Language Processing engine

# Projects

_Under Construction_